### PR TITLE
dev(frontend): add height padding and center pages

### LINKED ISSUE #80: preview appearance improvement
1. center the page horizontally
2. add a background color or border to page

### LINKED ISSUE #122: [FR] Show page breaks
In the current previewer, page breaks are not shown:
image

This makes it hard to understand why the spacing is as it is sometimes, which blurs the lines between spacing that needs fixing and spacing that looks the best given the pagebreaks. Could at least an option be added to allow showing a gap between pages?

### LINKED ISSUE #125: Resizing vscode panes is very laggy
Resizing panes in vscode causes the area of the preview window to change. The preview keeps getting updated while resizing, causing it to become very laggy.

**To Reproduce**
(See video as well)
1. Open a `.typ` file
2. Open the preview in a different pane.
3. Try resizing the code pane by dragging the separator with the mouse.
4. The resizing is very laggy.

https://github.com/Enter-tainer/typst-preview/assets/46323945/1331430e-1f57-4669-926f-75065e9551e4

**Expected behavior**
The preview doesn't cause the resizing to be laggy. (Using just the pdf viewer in vs code doesn't have this problem at all). I don't know enough of the technical implementation of this extension, to know what it "should" do, but I imagine it can postpone the (expensive) updates until the mouse is released again.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.82.1
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585

Date: 2023-09-08T08:41:36.199Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.4.6-76060406-generic
```

typst-preview extension version: `v0.8.0`

### PR DESCRIPTION
**Pull request by Myriad-Dreamin**
Without help of upstream typst.ts, It is still easier than imagined to decorate pages.

Though we leave customization out of current PR, I believe we have a good default setting:
+ The border width is window-aware.
+ The color page's border (page break) is fixed in `--vscode-editor-background`.
+ The page's background is fixed in `white` color, but you can still override a background at typst side, as the screenshot shown.
  via `set page(fill: rgb("#1a1b26").lighten(10%))`.
  
  
image

fix #125 fix #122 fix #80

### CODE REVIEW

File: addons/frontend/src/svg-doc.ts [hunk 1]
```diff
@@ -51,6 +55,10 @@ export class SvgDocument {
     /// for ctrl-wheel rescaling
     this.hookedElem.style.transformOrigin = "0px 0px";
 
+    /// Style fields
+    this.borderColor = getComputedStyle(document.documentElement).getPropertyValue('--vscode-editor-background')
+      || 'rgba(0, 0, 0, 0.5)';
```
Comment (Enter-tainer) [inline addons/frontend/src/svg-doc.ts:60]: how does rgba 000 0.5 looks like?

File: addons/frontend/src/svg-patch.ts [hunk 2]
```diff
@@ -332,8 +332,11 @@ export function patchRoot(prev: SVGElement, next: SVGElement) {
   /// Patch global svg resources
   patchSvgHeader(prev, next);
 
+  /// Hard replace elements that is not a `<g>` element.
+  const frozen = preReplaceNonSVGElements(prev, next, 3);
   /// Patch `<g>` children, call `reuseOrPatchElem` to patch.
   patchChildren(prev, next);
+  postReplaceNonSVGElements(prev, 3, frozen);
```
Comment (Enter-tainer) [inline addons/frontend/src/svg-patch.ts:339]: can you explain a bit about the magic number `3` here?

File: addons/frontend/src/svg-doc.ts (hunk 1 above)
Comment (Myriad-Dreamin) [reply addons/frontend/src/svg-doc.ts:60]: I guess your would love to set fallback color to `rgb(82, 86, 89)` (color name: `trout`), which is used by many PDF viewers.

File: addons/frontend/src/svg-patch.ts (hunk 2 above)
Comment (Myriad-Dreamin) [reply addons/frontend/src/svg-patch.ts]: Please see https://github.com/Enter-tainer/typst-preview/pull/120/commits/ba84d5079c66f2c594c449c69d1892a73a8efca9#diff-aa4f1a91aeb50ae8eb47dc4b1bb2f2322446c5dd5af2c1493b924433b16c2496R491

I have actively refactored some magic code and add some comments about this.

File: addons/frontend/index.html [hunk 3]
```diff
@@ -8,7 +8,24 @@
...
+        --vscode-editor-background,
+        rgb(82, 86, 89)
+      ) !important;
+    "
+  >
+    <div
+      id="imageContainer"
+      style="
+        background-color: var(
+          --vscode-editor-background,
```
Comment (Enter-tainer) [inline addons/frontend/index.html:25]: vscode-editor-background is good for dark mode. But for light theme like `Light+`, `Modern Light`, the background color is white, making the pages invisible again. Perhaps we can add a stroke around the rect?

Comment (Myriad-Dreamin) [reply addons/frontend/index.html:25]: good catch. we can retrieve a `preferred-theme` css variable, which typical has value of `dark` or `light`. We can add some graidient border to the rects in light themes.

Comment (Myriad-Dreamin) [reply addons/frontend/index.html:25]: I tested border, and whatever they look quite ugly. So I replace vscode-editor-background by vscode-sideBar-background (color of the explorer view). This is a great hack to assume the background of explorer view is not pure white, but I don't have one theme with that...

image

Comment (Enter-tainer) [reply addons/frontend/index.html]: image

It doesn't look great but better than none. But I don't see how pages are centered horizontally in this image. Is this included  in this PR?

I'm also thinking about what will it looks like by adding a box shadow to pages(rather than border stroke)

Comment (Myriad-Dreamin) [reply addons/frontend/index.html]: You've been triggering this bug, https://github.com/Enter-tainer/typst-preview/issues/86. The div is not resized according to the window sometimes.

Centering feature has been implemented here:

```js
/// center the page and add margin
const calculatedPaddedXRough = (newWidth - pageWidth) / 2;
const calculatedPaddedX = Math.abs(calculatedPaddedXRough) < 1e-3 ? 0 : calculatedPaddedXRough;
const calculatedPaddedY = accumulatedHeight + (i == 0 ? 0 : heightMargin);
const translateAttr = `translate(${calculatedPaddedX}, ${calculatedPaddedY})`;
```

image

image

Comment (Enter-tainer) [reply addons/frontend/index.html]: i'm sure i dont trigger that bug. I didnt even change the width of the preview panel. All I did is ctrl+wheel in the preview panel.

Comment (Myriad-Dreamin) [reply addons/frontend/index.html]: Okay, you did not say that you are zooming content. Indeed, the previous adjusting algorithm is broken again when we zoom out, and fixing is not included in this PR.

Comment (Enter-tainer) [reply addons/frontend/index.html]: okay so the "centering content horizontally" in this pr means that when the content is not zoomed, pages with smaller width will be centered? This is a bit off of what i initially expected.

**Comment by Myriad-Dreamin** [comment]
anyway, this PR also solves not ideal movement of viewport in zoom-out handling.
