### PR TITLE
fix: increase height of the SVG container before scrolling down

### LINKED ISSUE #128: Zoom causes panel to scroll up when the ctrl+wheel event has a relatively large `event.pageY`
**Describe the bug**
as title
**To Reproduce**
Preview a long document such as pkuthss and scroll the very end of preview panel. Use ctrl+wheel to scroll it.

**Package/Software version:**

This at least affects v0.8.0 and v0.8.1

### PR DESCRIPTION
**Pull request by Myriad-Dreamin**
fix #128.

Description: when somebody tries to zoom out, we has a wrong order of steps to go:

+ Initially, the viewport is at `(10000px, 0px)`, and the div element has a height of `10000px`.
+ To adjust position, js requests viewport to scroll down by `2500px`, however it hits the bottom of the div element, so it doesn't scroll down by `2500px` as expected.
+ change height of a div element to a larger value, e.g. from `10000px` to `12500px`.

Finally, the viewport is kept at the position `(10000px, 0px)` but the div element is resized to `12500px`.

If we reserve a larger height before scrolling, the wrong order steps doesn't bother.

### CODE REVIEW

File: addons/frontend/src/svg-doc.ts [hunk 1]
```diff
@@ -209,6 +212,11 @@ export class SvgDocument {
       svg.setAttribute("data-applied-height", appliedHeight);
       svg.setAttribute("height", `${scaledHeight}`);
     }
+
+    if (this.workaroundPreviewIssue128) {
+      this.hookedElem.style.marginBottom = `${scaledHeight}px`;
+      this.hookedElem.style.maxHeight = `${scaledHeight}px`;
+    }
```
Comment (Enter-tainer) [inline addons/frontend/src/svg-doc.ts:219]: How does this work?
